export const DATA_PART_3 = [
  {
    nGeral: 201,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11500",
    nome: "MAYCON CESAR DA SILVA LIMA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 202,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11559",
    nome: "RAIMUNDO NONATO LIMA DA SILVA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 203,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11653",
    nome: "RAIMUNDO PEREIRA DE SOUZA JUNIOR",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 204,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11554",
    nome: "RAULINO FERREIRA DA SILVA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 205,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11560",
    nome: "SIMVALDO PEREIRA LIMA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 206,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "10985",
    nome: "VALDIR PEREIRA DE LIMA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 207,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11296",
    nome: "WALACCE MACHADO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 208,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "10410",
    nome: "PAULO ROBERTO SOUZA SANTOS",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 209,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "10408",
    nome: "JOSÉ SEBASTIÃO SANTOS DA SILVA",
    funcao: "MOTORISTA OPERADOR",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO PERFURATRIZ",
    placa: "CP-0234",
  },
  {
    nGeral: 210,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11316",
    nome: "JARDELSON DE OLIVEIRA RODRIGUES",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "NMH-8E43",
  },
  {
    nGeral: 211,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11145",
    nome: "MARCELO SILVA FIGUEIRA",
    funcao: "MARTELETEIRO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 212,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11144",
    nome: "WEMERSON SILVA CORDEIRO",
    funcao: "MARTELETEIRO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 213,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "12140",
    nome: "JURANDIR FERREIRA DOS SANTOS",
    funcao: "MARTELETEIRO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 214,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "12139",
    nome: "LUCIANO ALVES DE SOUZA",
    funcao: "MARTELETEIRO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 215,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11182",
    nome: "EMERSON MEDEIROS DE OLIVEIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 216,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11162",
    nome: "JEFERSON ROCHA DIOGO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 217,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11183",
    nome: "WALISSON MACHADO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 218,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "12104",
    nome: "VILMAR REINALDO ALMEIDA",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 219,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11721",
    nome: "JEFERSON RIBEIRO RODRIGUES",
    funcao: "MOTORISTA DE CAMINHAO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO 8X4 PRANCHA BI TRUCK",
    placa: "HJZ-4I51",
  },
  {
    nGeral: 220,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11723",
    nome: "MARCOS VENICIUS PEREIRA DOS ANJOS",
    funcao: "MOTORISTA OPERADOR",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO PERFURATRIZ",
    placa: "CP-0356",
  },
  {
    nGeral: 221,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "10901",
    nome: "PEDRO HENRIQUE CORREIA SILVA DE SOUSA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "OMU-9D39",
  },
  {
    nGeral: 222,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "12067",
    nome: "MATHEUS LOPES DA SILVA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 223,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11417",
    nome: "ALISON DE CARVALHO VIEIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 224,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "12190",
    nome: "ANDRE FELIPE MEDEIROS DE OLIVEIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 225,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11422",
    nome: "DEIVID FERREIRA LOPES",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 226,
    eap: "1202",
    desc: "ESCAVAÇÃO ESTAIADA/AUTOPORTANTE",
    matricula: "11421",
    nome: "LUCAS MARIANO MATINS FERREIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 227,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "10712",
    nome: "WILDER DE SOUZA CARDOSO",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 228,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "11136",
    nome: "ERINALDO DE OLIVEIRA LIMA",
    funcao: "OPERADOR DE MAQUINAS VIII",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "ESCAVADEIRA HIDRAULICA",
    placa: "EH-0214",
  },
  {
    nGeral: 229,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "10765",
    nome: "JOSE AUGUSTO VIEIRA DE OLIVEIRA",
    funcao: "OPERADOR DE MAQUINAS VIII",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "ESCAVADEIRA HIDRAULICA",
    placa: "EH-0536",
  },
  {
    nGeral: 230,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "10995",
    nome: "NATANIEL DOS SANTOS PEREIRA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CARROCERIA",
    placa: "NMH-5D45",
  },
  {
    nGeral: 231,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "12108",
    nome: "FRANCINALDO FERNANDES FERREIRA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHONETE 4X4",
    placa: "SHR-1D19",
  },
  {
    nGeral: 232,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "11299",
    nome: "IGOR MONSORES BORGES",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 233,
    eap: "1206",
    desc: "FUNDAÇÕES HELICOIDAIS",
    matricula: "11309",
    nome: "JOSE SEBASTIAO DOS SANTOS SILVA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 234,
    eap: "1103",
    desc: "CONSTRUÇÃO DE ACESSO",
    matricula: "11418",
    nome: "JOSE CARLOS LUIZ DA SILVA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 235,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "10365",
    nome: "DANIEL BARBOSA DE AGUIAR",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 236,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "8398",
    nome: "FRANCISCO DE CHAGAS ALVES SOUZA",
    funcao: "MOTORISTA OPERADOR DE MUNCK",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x4 MUNCK 22T",
    placa: "QYT-3A45",
  },
  {
    nGeral: 237,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "10674",
    nome: "DANIEL DA SILVA CORDEIRO",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "PEF-4H50",
  },
  {
    nGeral: 238,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11310",
    nome: "LEANDRO BENEVIDES DA ROCHA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 239,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "10412",
    nome: "OZIEL RIBEIRO DA SILVA",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 240,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11195",
    nome: "DOUGLAS JOAO NASCIMENTO",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x4 MUNCK 45T",
    placa: "RVF-6E43",
  },
  {
    nGeral: 241,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "10887",
    nome: "JANILSON MATOS SOUZA",
    funcao: "MOTORISTA OPERADOR DE MUNCK",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x4 MUNCK 45T / C SUP 07L",
    placa: "OBV-7J21",
  },
  {
    nGeral: 242,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11200",
    nome: "LUCAS MARIANO MARTINS FERREIRA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 243,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11184",
    nome: "RAFAEL DA SILVA PEREIRA",
    funcao: "OPERADOR DE MOTOSSERRA",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 244,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11293",
    nome: "MARCOS GOMES BARBOSA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 245,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11294",
    nome: "ADRIANO SILVA AGUIAR",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 246,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11175",
    nome: "RICARDO MATOS DE SOUZA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 247,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11176",
    nome: "ELIAS FREITAS MACEDO",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 248,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11177",
    nome: "VANDERLEI FERNANDES SILVA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 249,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11179",
    nome: "MARCELO SILVA FIGUEIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 250,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11180",
    nome: "MARCOS VENICIUS PEREIRA ANJOS",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 251,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11140",
    nome: "RONAILSON BARROS SILVA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 252,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11141",
    nome: "JEFERSON RIBEIRO RODRIGUES",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 253,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11147",
    nome: "JOSE AUGUSTO VIEIRA OLIVEIRA",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 254,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11148",
    nome: "WILDER SOUZA CARDOSO",
    funcao: "TOPOGRAFO VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x2 MUNCK 45T",
    placa: "TAG-034",
  },
  {
    nGeral: 255,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11150",
    nome: "FRANCINALDO FERNANDES FERREIRA",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "ESCAVADEIRA HIDRAULICA",
    placa: "EH-8314",
  },
  {
    nGeral: 256,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11151",
    nome: "ERINALDO OLIVEIRA LIMA",
    funcao: "OPERADOR DE MAQUINAS VIII",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "KGO-7I02",
  },
  {
    nGeral: 257,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11152",
    nome: "CLEMILSON SILVA SANTOS",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 258,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11154",
    nome: "ESPEDITO MANOEL ALVES",
    funcao: "OPERADOR DE MOTOSSERA VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 259,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11155",
    nome: "JOAO ALCIDES BRITO",
    funcao: "PEDREIRO V",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 260,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11156",
    nome: "ALEXSANDER ROCHA DIOGO",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 261,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11157",
    nome: "LUIZ ARTHUR GOMES SEVERO",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 262,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11158",
    nome: "DIOGENES PEDRO RIBEIRO",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 263,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11159",
    nome: "JONAD JEFESON ARAUJO MELO",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 264,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11160",
    nome: "RENATO LEMOS FONSECA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 265,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11163",
    nome: "LINEKER SILVA GUIMARAES",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 266,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11164",
    nome: "RICARDO MATOS SANTANA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 267,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11166",
    nome: "MATHEUS LOPES SILVA",
    funcao: "AUXILIAR DE TOPOGRAFIA",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 268,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11167",
    nome: "ALISON CARVALHO VIEIRA",
    funcao: "TOPOGRAFO VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHONETE 4X4",
    placa: "SHR-1D19",
  },
  {
    nGeral: 269,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11168",
    nome: "DEIVID FERREIRA LOPES",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "ESCAVADEIRA HIDRAULICA",
    placa: "EH-0536",
  },
  {
    nGeral: 270,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11169",
    nome: "LUCAS MARIANO MATINS FERREIRA",
    funcao: "OPERADOR DE MAQUINAS VIII",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "PEF-4H50",
  },
  {
    nGeral: 271,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11170",
    nome: "ELIAS FREITAS MACEDO",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 272,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11171",
    nome: "VANDERLEI FERNANDES SILVA",
    funcao: "OPERADOR DE MOTOSSERA VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 273,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11172",
    nome: "THIAGO SILVA CARVALHO",
    funcao: "PEDREIRO V",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 274,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11173",
    nome: "MARCELO SILVA FIGUEIRA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 275,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11335",
    nome: "ANTONY GABRIEL OLIVEIRA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 276,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11336",
    nome: "MAYLON NASCIMENTO SANTOS",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 277,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11337",
    nome: "JOSE AUGUSTO VIEIRA FERNANDES",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 278,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11338",
    nome: "JARDELSON OLIVEIRA RODRIGUES",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 279,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11340",
    nome: "VALISSON MACHADO",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 280,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11341",
    nome: "WALACCE MACHADO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 281,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11342",
    nome: "LUCAS FONSECA MACHADO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 282,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11344",
    nome: "PAULO SIDNEY FAUSTINO CAMPOS",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 283,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11345",
    nome: "LEANDRO SANTOS NUNES",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 284,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11346",
    nome: "DANIEL LUCAS",
    funcao: "MOTORISTA OP DE BETONEIRA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "PASSAGEIRO ONIBUS 41L",
    placa: "BUS-012",
  },
  {
    nGeral: 285,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11347",
    nome: "JEFERSON ROCHA DIOGO",
    funcao: "MOTORISTA OPERADOR DE BETONEIRA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO BETONEIRA",
    placa: "BET-084",
  },
  {
    nGeral: 286,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11348",
    nome: "AMARILDO BATISTA MOURA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "OMU-9D39",
  },
  {
    nGeral: 287,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11349",
    nome: "JOICKSON MONSORES BORGES",
    funcao: "PEDREIRO V",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 288,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11350",
    nome: "RENATO SIQUEIRA",
    funcao: "PEDREIRO V",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 289,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11352",
    nome: "VANDERLEI FERNANDES SILVA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 290,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11353",
    nome: "RAFAEL DA SILVA PEREIRA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 291,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11354",
    nome: "MARCOS GOMES BARBOSA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 292,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11356",
    nome: "ADRIANO SILVA AGUIAR",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 293,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11358",
    nome: "RICARDO MATOS DE SOUZA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 294,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11361",
    nome: "ELIAS FREITAS MACEDO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 295,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11362",
    nome: "VANDERLEI FERNANDES SILVA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 296,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11363",
    nome: "THIAGO SILVA CARVALHO",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 297,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11364",
    nome: "MARCELO SILVA FIGUEIRA",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 298,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11365",
    nome: "MARCOS VENICIUS PEREIRA ANJOS",
    funcao: "AUXILIAR DE TOPOGRAFIA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO BETONEIRA",
    placa: "BET-085",
  },
  {
    nGeral: 299,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11366",
    nome: "RONAILSON BARROS SILVA",
    funcao: "MOTORISTA OPERADOR DE BETONEIRA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 300,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11367",
    nome: "JEFERSON RIBEIRO RODRIGUES",
    funcao: "PEDREIRO V",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
];
