DISPLAY_NAME=Gestao Virtual
DESCRIPTION=Sistema Gestão Virtual (API + Frontend Unificado)
MAIN=squarecloud.unified.start.cjs
MEMORY=3072
VERSION=recommended
START=node squarecloud.unified.start.cjs
AUTORESTART=true
SUBDOMAIN=gestao-virtual
WEBSITE=true
