DISPLAY_NAME=Gestao Virtual
DESCRIPTION=Sistema Gestão Virtual (API + Frontend Unificado)
MAIN=start.js
MEMORY=3072
VERSION=recommended
START=node start.js
AUTORESTART=true
SUBDOMAIN=gestao-virtual
WEBSITE=true
