import { PhaseConfig } from '@/components/map/CableConfigModal'

export const DEFAULT_PHASES: PhaseConfig[] = [
  {
    id: 'OPGW_L',
    name: 'OPGW (Esquerda)',
    enabled: true,
    color: [203, 213, 225],
    tension: 1200,
    verticalOffset: 40,
    horizontalOffset: -4,
    relativeHeight: 100,
    cableCount: 1,
    bundleSpacing: 0.4,
    width: 0.1,
    spacerInterval: 40,
    spacerSize: 0.6,
    spacerThickness: 0.15,
    spacerColor: [255, 80, 0],
    cableType: '',
    signalSpheresEnabled: true,
    signalSphereInterval: 40,
    signalSphereSize: 0.6,
    signalSphereColor: [255, 200, 200],
  },
  {
    id: 'OPGW_R',
    name: 'OPGW (Direita)',
    enabled: true,
    color: [203, 213, 225],
    tension: 1200,
    verticalOffset: 40,
    horizontalOffset: 4,
    relativeHeight: 100,
    cableCount: 1,
    bundleSpacing: 0.4,
    width: 0.1,
    spacerInterval: 40,
    spacerSize: 0.6,
    spacerThickness: 0.15,
    spacerColor: [255, 80, 0],
    cableType: '',
    signalSpheresEnabled: true,
    signalSphereInterval: 40,
    signalSphereSize: 0.6,
    signalSphereColor: [255, 200, 200],
  },
  {
    id: 'A_L',
    name: 'Fase A (Esq Superior)',
    enabled: true,
    color: [148, 163, 184],
    tension: 1800,
    verticalOffset: 33,
    horizontalOffset: -6,
    relativeHeight: 100,
    cableCount: 4,
    bundleSpacing: 0.4,
    width: 0.15,
    spacerInterval: 30,
    spacerSize: 1.1,
    spacerThickness: 0.2,
    spacerColor: [20, 20, 20],
    cableType: '',
  },
  {
    id: 'B_L',
    name: 'Fase B (Esq Média)',
    enabled: true,
    color: [203, 213, 225],
    tension: 1800,
    verticalOffset: 25,
    horizontalOffset: -6,
    relativeHeight: 100,
    cableCount: 4,
    bundleSpacing: 0.4,
    width: 0.15,
    spacerInterval: 30,
    spacerSize: 1.1,
    spacerThickness: 0.2,
    spacerColor: [20, 20, 20],
    cableType: '',
  },
  {
    id: 'C_L',
    name: 'Fase C (Esq Inferior)',
    enabled: true,
    color: [71, 85, 105],
    tension: 1800,
    verticalOffset: 17,
    horizontalOffset: -6,
    relativeHeight: 100,
    cableCount: 4,
    bundleSpacing: 0.4,
    width: 0.15,
    spacerInterval: 30,
    spacerSize: 1.1,
    spacerThickness: 0.2,
    spacerColor: [20, 20, 20],
    cableType: '',
  },
  {
    id: 'A_R',
    name: 'Fase A (Dir Superior)',
    enabled: true,
    color: [148, 163, 184],
    tension: 1800,
    verticalOffset: 33,
    horizontalOffset: 6,
    relativeHeight: 100,
    cableCount: 4,
    bundleSpacing: 0.4,
    width: 0.15,
    spacerInterval: 30,
    spacerSize: 1.1,
    spacerThickness: 0.2,
    spacerColor: [20, 20, 20],
    cableType: '',
  },
  {
    id: 'B_R',
    name: 'Fase B (Dir Média)',
    enabled: true,
    color: [203, 213, 225],
    tension: 1800,
    verticalOffset: 25,
    horizontalOffset: 6,
    relativeHeight: 100,
    cableCount: 4,
    bundleSpacing: 0.4,
    width: 0.15,
    spacerInterval: 30,
    spacerSize: 1.1,
    spacerThickness: 0.2,
    spacerColor: [20, 20, 20],
    cableType: '',
  },
  {
    id: 'C_R',
    name: 'Fase C (Dir Inferior)',
    enabled: true,
    color: [71, 85, 105],
    tension: 1800,
    verticalOffset: 17,
    horizontalOffset: 6,
    relativeHeight: 100,
    cableCount: 4,
    bundleSpacing: 0.4,
    width: 0.15,
    spacerInterval: 30,
    spacerSize: 1.1,
    spacerThickness: 0.2,
    spacerColor: [20, 20, 20],
    cableType: '',
  },
]

export const MAPBOX_TOKEN = import.meta.env.VITE_MAPBOX_API_KEY
export const TOWER_MODEL_URL = '/assets/models/towers/scene.gltf'
export const INITIAL_VIEW_STATE = {
  longitude: -51.9253,
  latitude: -14.235,
  zoom: 4,
  pitch: 45,
  bearing: 0,
}
