export const DATA_PART_4 = [
  {
    nGeral: 301,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11368",
    nome: "MARCOS ANTONIO MENDES DA SILVA",
    funcao: "ARMADOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 302,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11369",
    nome: "GERALDO SILVA",
    funcao: "CARPINTEIRO IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 303,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11370",
    nome: "JOSE CARVALHO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 304,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11371",
    nome: "PEDRO SANTOS",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 305,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11372",
    nome: "ALBERTO FARIAS",
    funcao: "ENCARREGADO DE OBRA CIVIL VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 306,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11373",
    nome: "RAIMUNDO SILVA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "JEEP 12 LUGARES",
    placa: "JEP-011",
  },
  {
    nGeral: 307,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11374",
    nome: "JOSE OLIVEIRA",
    funcao: "OPERADOR DE MOTOSSERA VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 308,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11376",
    nome: "MARCO SOUZA",
    funcao: "OPERADOR DE MOTOSSERRA",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 309,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11377",
    nome: "DANIEL LIMA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 310,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11378",
    nome: "RICARDO CASTRO",
    funcao: "ENC.DE PÁTEO III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 311,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11379",
    nome: "FERNANDO MARTINS",
    funcao: "MOTORISTA OPERADOR DE MUNCK",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x4 MUNCK 45T / C SUP 07L",
    placa: "OBV-7J21",
  },
  {
    nGeral: 312,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11380",
    nome: "MARCELO SILVA",
    funcao: "MOTORISTA OPERADOR DE MUNK II",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 313,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11381",
    nome: "DANIEL REIS",
    funcao: "MOTORISTA OPERADOR II",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 314,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11382",
    nome: "JOSE COSTA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 315,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11383",
    nome: "LUCAS MARIANO",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 316,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11384",
    nome: "WALTER GOMES",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 317,
    eap: "1204",
    desc: "PREPARAÇÃO/USINA CONC/CARP./CONCRETAGEM",
    matricula: "11385",
    nome: "SIDNEY LINS",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 318,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11386",
    nome: "FERNANDO FERREIRA",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 319,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11387",
    nome: "GABRIEL OLIVEIRA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "NMH-8E43",
  },
  {
    nGeral: 320,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11388",
    nome: "MAYCON CESAR",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 321,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11389",
    nome: "ANDRE FELIPE",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 322,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11390",
    nome: "ALISON CARVALHO",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 323,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11391",
    nome: "DEIVID FERREIRA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "PEF-4H50",
  },
  {
    nGeral: 324,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11392",
    nome: "LUCAS MARIANO",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 325,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11393",
    nome: "DANIEL DA SILVA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 326,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11394",
    nome: "MARCELO SILVA",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 327,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11395",
    nome: "VANDERLEI FERNANDES",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "KGO-7I02",
  },
  {
    nGeral: 328,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11396",
    nome: "JOSE COSTA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 329,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11397",
    nome: "RAFAEL HONORATO",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 330,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11398",
    nome: "EDILO COSTA",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 331,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11399",
    nome: "LUCIANO HENRIQUE",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 332,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11400",
    nome: "JULIANO BARBOSA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "OMU-9D39",
  },
  {
    nGeral: 333,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11401",
    nome: "RAILSON RAMIRES",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 334,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11402",
    nome: "AILSON LIMA",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 335,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11403",
    nome: "ALVARO COSTA",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 336,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11404",
    nome: "JAILTON FRANKLIN",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "RVF-6E43",
  },
  {
    nGeral: 337,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11405",
    nome: "JOAO IVO",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 338,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11406",
    nome: "JOSE ANDERSON",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 339,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11407",
    nome: "JOSIVANIO JOSE",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 340,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11408",
    nome: "JUCIER ROGERIO",
    funcao: "OPERADOR DE MAQUINAS VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "TRATOR PNEU 4X4",
    placa: "TRA-843",
  },
  {
    nGeral: 341,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11409",
    nome: "JUNIOR CESAR",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 342,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11410",
    nome: "MARCOS ANTONIO",
    funcao: "OPERADOR DE TRATOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 343,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11411",
    nome: "RAIMUNDO NONATO",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 344,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11412",
    nome: "SIMVALDO PEREIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 345,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11413",
    nome: "VALDIR PEREIRA",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 346,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11414",
    nome: "PAULO ROBERTO SOUZA",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 347,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11415",
    nome: "JOSE SEBASTIAO",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x4 MUNCK 45T",
    placa: "MUM-8432",
  },
  {
    nGeral: 348,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11416",
    nome: "JARDELSON OLIVEIRA",
    funcao: "MOTORISTA",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 349,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11419",
    nome: "MARCELO SILVA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 350,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11420",
    nome: "WEMERSON SILVA",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 351,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11423",
    nome: "JURANDIR FERREIRA",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 352,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11424",
    nome: "LUCIANO ALVES",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 353,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11425",
    nome: "EMERSON MEDEIROS",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 354,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11426",
    nome: "JEFERSON ROCHA",
    funcao: "MOTORISTA DE CAMINHÃO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "JEEP 12 LUGARES",
    placa: "JEP-045",
  },
  {
    nGeral: 355,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11427",
    nome: "WALISSON MACHADO",
    funcao: "OPERADOR DE MAQUINAS VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 356,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11428",
    nome: "VILMAR REINALDO",
    funcao: "MEIO OFICIAL MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 357,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11429",
    nome: "JEFERSON RIBEIRO",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 358,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11430",
    nome: "MARCOS VENICIUS",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 359,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11431",
    nome: "PEDRO HENRIQUE",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 360,
    nParcial: 1,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11432",
    nome: "MATHEUS LOPES",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 361,
    nParcial: 2,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11433",
    nome: "ALISON CARVALHO",
    funcao: "MOTORISTA I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TOCO CABINE SUPLEMENTAR 23L",
    placa: "NMH-8E43",
  },
  {
    nGeral: 362,
    nParcial: 3,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11434",
    nome: "DEIVID FERREIRA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 363,
    nParcial: 4,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11435",
    nome: "LUCAS MARIANO",
    funcao: "OPERADOR DE TRATOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 364,
    nParcial: 5,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11436",
    nome: "ELIAS FREITAS",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 365,
    nParcial: 6,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11438",
    nome: "VANDERLEI FERNANDES",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 366,
    nParcial: 1,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11439",
    nome: "THIAGO SILVA",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 367,
    nParcial: 2,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11440",
    nome: "MARCELO SILVA",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 368,
    nParcial: 3,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11442",
    nome: "MARCOS VENICIUS",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 369,
    nParcial: 1,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11443",
    nome: "RONAILSON BARROS",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 370,
    nParcial: 2,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11444",
    nome: "JEFERSON RIBEIRO",
    funcao: "OPERADOR DE GUINDASTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "GUINDASTE",
    placa: "GUI-8234",
  },
  {
    nGeral: 371,
    nParcial: 3,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11445",
    nome: "ADRIANO SILVA",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 372,
    nParcial: 5,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11447",
    nome: "MAYLON NASCIMENTO",
    funcao: "MONTADOR VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 373,
    nParcial: 6,
    eap: "1405",
    desc: "REVISÃO ESTRUTURAS METÁLICAS AUTOPORTANTES/ESTAIADAS",
    matricula: "11448",
    nome: "ANTONY GABRIEL",
    funcao: "AJUDANTE",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 374,
    nParcial: 1,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11449",
    nome: "JOSE AUGUSTO",
    funcao: "ENCARREGADO DE MONTAGEM AT",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 375,
    nParcial: 2,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11450",
    nome: "JARDELSON OLIVEIRA",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x2 MUNCK 45T",
    placa: "MUN-5431",
  },
  {
    nGeral: 376,
    nParcial: 3,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11451",
    nome: "VALISSON MACHADO",
    funcao: "MOTORISTA III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 377,
    nParcial: 4,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11452",
    nome: "WALACCE MACHADO",
    funcao: "MONTADOR AT VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 378,
    nParcial: 5,
    eap: "1403",
    desc: "MONTAGEM DE TORRE ESTAIADA/AUTOPORTANTE",
    matricula: "11453",
    nome: "LUCAS FONSECA",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 379,
    nParcial: 1,
    eap: "1502",
    desc: "DISTRIBUIÇÃO DE BOBINAS E ACESSÓRIOS",
    matricula: "11454",
    nome: "PAULO SIDNEY",
    funcao: "MOTORISTA OPERADOR DE MUNCK",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x2 MUNCK 45T",
    placa: "MUN-0359",
  },
  {
    nGeral: 380,
    nParcial: 2,
    eap: "1502",
    desc: "DISTRIBUIÇÃO DE BOBINAS E ACESSÓRIOS",
    matricula: "11455",
    nome: "LEANDRO SANTOS",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 381,
    nParcial: 3,
    eap: "1502",
    desc: "DISTRIBUIÇÃO DE BOBINAS E ACESSÓRIOS",
    matricula: "11456",
    nome: "DANIEL LUCAS",
    funcao: "MONTADOR II",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 382,
    nParcial: 4,
    eap: "1502",
    desc: "DISTRIBUIÇÃO DE BOBINAS E ACESSÓRIOS",
    matricula: "11457",
    nome: "JEFERSON ROCHA",
    funcao: "MONTADOR VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 383,
    nParcial: 1,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11458",
    nome: "AMARILDO BATISTA",
    funcao: "ENCARREGADO DE MONTAGEM I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 384,
    nParcial: 2,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11459",
    nome: "JOICKSON MONSORES",
    funcao: "MOTORISTA OPERADOR DE MUNCK IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
    equ: "CAMINHÃO TRUCK 6x4 MUNCK 33T",
    placa: "MUN-8234",
  },
  {
    nGeral: 385,
    nParcial: 3,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11460",
    nome: "RENATO SIQUEIRA",
    funcao: "MONTADOR ESPOREIRO III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 386,
    nParcial: 4,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11461",
    nome: "VANDERLEI FERNANDES",
    funcao: "MONTADOR III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 387,
    nParcial: 5,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11462",
    nome: "RAFAEL DA SILVA",
    funcao: "MONTADOR VII",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 388,
    nParcial: 1,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11463",
    nome: "MARCOS GOMES",
    funcao: "ENCARREGADO DE LANÇAMENTO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 389,
    nParcial: 2,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11464",
    nome: "ADRIANO SILVA",
    funcao: "MONTADOR III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 390,
    nParcial: 3,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11465",
    nome: "RICARDO MATOS",
    funcao: "MONTADOR VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 391,
    nParcial: 4,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11466",
    nome: "ELIAS FREITAS",
    funcao: "MONTADOR",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 392,
    nParcial: 1,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11467",
    nome: "VANDERLEI FERNANDES",
    funcao: "OPERADOR DE MAQUINAS VIII",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 393,
    nParcial: 2,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11468",
    nome: "THIAGO SILVA",
    funcao: "MONTADOR III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 394,
    nParcial: 3,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11469",
    nome: "MARCELO SILVA",
    funcao: "MONTADOR VI",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 395,
    nParcial: 4,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11470",
    nome: "MARCOS VENICIUS",
    funcao: "OPERADOR DE TRATOR IV",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 396,
    nParcial: 5,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO PILOTO / PR-RAIOS",
    matricula: "11471",
    nome: "RONAILSON BARROS",
    funcao: "AJUDANTE AT III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 397,
    nParcial: 1,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO OPGW / FREIO",
    matricula: "11472",
    nome: "JEFERSON RIBEIRO",
    funcao: "ENCARREGADO DE LANÇAMENTO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 398,
    nParcial: 2,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO OPGW / FREIO",
    matricula: "11473",
    nome: "RODRIGO SALU",
    funcao: "MONTADOR II",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 399,
    nParcial: 3,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO OPGW / FREIO",
    matricula: "11474",
    nome: "JARDESON GABRIEL",
    funcao: "MONTADOR III",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
  {
    nGeral: 400,
    nParcial: 1,
    eap: "1504",
    desc: "LANÇAMENTO DE CABO OPGW / PULLER",
    matricula: "11475",
    nome: "MURILO BRENER",
    funcao: "ENCARREGADO DE LANÇAMENTO I",
    moe: "MOD",
    local: "PATY DO ALFERES-RJ",
  },
];
