export const DATA_PART_1 = [
  {
    nGeral: 1,
    eap: "2009",
    desc: "LT-GESTÃO DA OBRA",
    matricula: "9000051",
    nome: "HUGO MIRANDA BASTOS DE OLIVEIRA",
    funcao: "ENGENHEIRO RESIDENTE",
  },
  {
    nGeral: 2,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "90000233",
    nome: "CHARLES SILVA DE SOUZA",
    funcao: "COORDENADOR DE OBRAS",
  },
  {
    nGeral: 3,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "9000017",
    nome: "CARLOS ANDRE SANTOS",
    funcao: "ENGENHEIRO DE PRODUCAO",
  },
  {
    nGeral: 4,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "9000085",
    nome: "NELTON FERNANDES FERREIRA LOPES",
    funcao: "SUPERVISOR DE LANÇAMENTO",
  },
  {
    nGeral: 5,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "9000126",
    nome: "BENEDITO VIEIRA DANTAS",
    funcao: "SUPERVISOR DE CIVIL",
  },
  {
    nGeral: 6,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "9000026",
    nome: "DANILO MARCIANO MARTINS FERREIRA",
    funcao: "SUPERVISOR DE CIVIL",
  },
  {
    nGeral: 7,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "9000093",
    nome: "REGINALDO ALEXANDRE DA SILVA",
    funcao: "SUPERVISOR DE MONTAGEM",
  },
  {
    nGeral: 8,
    eap: "2016",
    desc: "LT-PRODUÇÃO",
    matricula: "10698",
    nome: "PEDRO LUIZ ALVES CARDOSO AMBROSIO",
    funcao: "AUXILIAR TECNICO",
  },
  {
    nGeral: 9,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "10573",
    nome: "JOSE WILTON DOS SANTOS OLIVEIRA",
    funcao: "ENCARREGADO DE RECURSOS HUMANOS",
  },
  {
    nGeral: 10,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "10702",
    nome: "FELIPE PIVETTA DE CARVALHO",
    funcao: "ANALISTA TECNICO",
  },
  {
    nGeral: 11,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "10661",
    nome: "RENATA CRISTINA CAETANO",
    funcao: "ASSISTENTE ADMINISTRATIVO I",
  },
  {
    nGeral: 12,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "10624",
    nome: "MAYARA DA SILVA BARROS",
    funcao: "AUX.ADMINISTRATIVO",
  },
  {
    nGeral: 13,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "12193",
    nome: "EWYNER MARCELINO RODRIGUES",
    funcao: "ASSISTENTE ADMINISTRATIVO IV",
  },
  {
    nGeral: 14,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "10613",
    nome: "BEATRIZ PEREIRA DA SILVA",
    funcao: "AUX DE SERVICOS GERAIS III",
  },
  {
    nGeral: 15,
    eap: "2012",
    desc: "LT-RECURSOS HUMANOS",
    matricula: "11284",
    nome: "HAYLAN PIMENTEL DA SILVA",
    funcao: "AJUDANTE",
  },
  {
    nGeral: 16,
    eap: "2011",
    desc: "LT-ADMINISTRAÇÃO",
    matricula: "9000131",
    nome: "RIVADARIO MEDEIROS DE OLIVEIRA",
    funcao: "SUPERVISOR ADMINISTRATIVO",
  },
  {
    nGeral: 17,
    eap: "2011",
    desc: "LT-ADMINISTRAÇÃO",
    matricula: "9000130",
    nome: "MARCIO DE AGUIAR DO ANJOS",
    funcao: "ANALISTA DE TI",
  },
  {
    nGeral: 18,
    eap: "2011",
    desc: "LT-ADMINISTRAÇÃO",
    matricula: "11211",
    nome: "SALATIEL SILVA SOUZA",
    funcao: "ASSISTENTE ADMINISTRATIVO IV",
  },
  {
    nGeral: 19,
    eap: "2011",
    desc: "LT-ADMINISTRAÇÃO",
    matricula: "11178",
    nome: "JOAO VICTOR VIEIRA DOS SANTOS",
    funcao: "AJUDANTE",
  },
  {
    nGeral: 20,
    eap: "2010",
    desc: "LT-SEÇÃO TÉCNICA E PLANEJAMENTO",
    matricula: "9000118",
    nome: "WILDSON WELLINGTON SILVA",
    funcao: "ENGENHEIRO DE PLANEJAMENTO",
  },
  {
    nGeral: 21,
    eap: "2010",
    desc: "LT-SEÇÃO TÉCNICA E PLANEJAMENTO",
    matricula: "9000127",
    nome: "BRENDA RENATA DA SILVA GAMITO DE CASTRO",
    funcao: "COORDENADOR PLANEJAMENTO",
  },
  {
    nGeral: 22,
    eap: "2010",
    desc: "LT-SEÇÃO TÉCNICA E PLANEJAMENTO",
    matricula: "7643",
    nome: "JULIANO FREITAS DE MORAES",
    funcao: "TECNICO DE PLANEJAMENTO",
  },
  {
    nGeral: 23,
    eap: "2010",
    desc: "LT-SEÇÃO TÉCNICA E PLANEJAMENTO",
    matricula: "9099",
    nome: "RODRIGO SALU RODRIGUES",
    funcao: "TECNICO DE PLANEJAMENTO III",
  },
  {
    nGeral: 24,
    eap: "2010",
    desc: "LT-SEÇÃO TÉCNICA E PLANEJAMENTO",
    matricula: "9000054",
    nome: "JARDESON GABRIEL RODMANN",
    funcao: "ASSITENTE TÉCNICO",
  },
  {
    nGeral: 25,
    eap: "2010",
    desc: "LT-SEÇÃO TÉCNICA E PLANEJAMENTO",
    matricula: "10740",
    nome: "MURILO BRENER LOPES VIEIRA",
    funcao: "TECNICO DE MATERIAIS",
  },
  {
    nGeral: 26,
    eap: "2020",
    desc: "LT-QUALIDADE",
    matricula: "11375",
    nome: "TAILTON LUCIANO DE OLIVEIRA",
    funcao: "SUPERVISOR DE QUALIDADE PL",
  },
  {
    nGeral: 27,
    eap: "2020",
    desc: "LT-QUALIDADE",
    matricula: "11912",
    nome: "TAILSON GONCALVES DA CONCEICAO",
    funcao: "TECNICO EM QUALIDADE JR",
  },
  {
    nGeral: 28,
    eap: "2020",
    desc: "LT-QUALIDADE",
    matricula: "11801",
    nome: "JOSE CARLOS DA SILVA",
    funcao: "MOTORISTA III",
  },
  {
    nGeral: 29,
    eap: "2018",
    desc: "LT-MEIO AMBIENTE",
    matricula: "9000122",
    nome: "ADRIANO PAVANI NOCCHI",
    funcao: "ENGENHEIRO FLORESTAL",
  },
  {
    nGeral: 30,
    eap: "2018",
    desc: "LT-MEIO AMBIENTE",
    matricula: "10699",
    nome: "DANILLO FERRAO DE SOUZA",
    funcao: "TECNICO DE MEIO AMBIENTE PL",
  },
  {
    nGeral: 31,
    eap: "2018",
    desc: "LT-MEIO AMBIENTE",
    matricula: "11800",
    nome: "GEDSON DA SILVA RIBEIRO",
    funcao: "TECNICO DE MEIO AMBIENTE PL",
  },
  {
    nGeral: 32,
    eap: "2018",
    desc: "LT-MEIO AMBIENTE",
    matricula: "11890",
    nome: "JACKSON REINALDO NASCIMENTO DOS SANTOS",
    funcao: "TECNICO FUNDIARIO VI",
  },
];
