export enum Role {
    HELPER_SYSTEM = 'HELPER_SYSTEM',
    ADMIN = 'ADMIN',
    TI_SOFTWARE = 'TI_SOFTWARE',
    COMPANY_ADMIN = 'COMPANY_ADMIN',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    SITE_MANAGER = 'SITE_MANAGER',
    SUPERVISOR = 'SUPERVISOR',
    OPERATIONAL = 'OPERATIONAL',
    VIEWER = 'VIEWER',
}

export enum AccountStatus {
    PENDING_VERIFICATION = 'PENDING_VERIFICATION',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    SUSPENDED = 'SUSPENDED',
    BLOCKED = 'BLOCKED'
}
