export enum Role {
    USER = 'USER',
    ADMIN = 'ADMIN',
    MODERATOR = 'MODERATOR',
    MANAGER = 'MANAGER',
    SUPERVISOR = 'SUPERVISOR',
    TECHNICIAN = 'TECHNICIAN',
    OPERATOR = 'OPERATOR',
    SUPER_ADMIN = 'SUPER_ADMIN',
    SUPER_ADMIN_GOD = 'SUPER_ADMIN_GOD',
    SOCIO_DIRETOR = 'SOCIO_DIRETOR',
    HELPER_SYSTEM = 'HELPER_SYSTEM',
    WORKER = 'WORKER',
    TI_SOFTWARE = 'TI_SOFTWARE',
    GESTOR_PROJECT = 'GESTOR_PROJECT',
    GESTOR_CANTEIRO = 'GESTOR_CANTEIRO',
    VIEWER = 'VIEWER',
    GUEST = 'GUEST',
    COORDINATOR = 'COORDINATOR',
    SUPERADMIN = 'SUPER_ADMIN' // Alias
}

export enum AccountStatus {
    PENDING_VERIFICATION = 'PENDING_VERIFICATION',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    SUSPENDED = 'SUSPENDED',
    BLOCKED = 'BLOCKED'
}
